"""Initial Migration

Revision ID: 27b9d01347ea
Revises: 
Create Date: 2025-12-18 07:15:16.815917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27b9d01347ea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_i18n_perf')
    op.drop_table('test_compute_a')
    op.drop_table('test_tag')
    op.drop_table('res_partner_test')
    op.drop_table('dx_song')
    op.drop_table('rls_doc')
    op.drop_table('perf_tag')
    op.drop_table('perf_record')
    op.drop_table('perf_record_tag_rel')
    op.drop_table('test_realtime')
    op.drop_table('test_perf')
    op.drop_table('test_fls')
    op.drop_table('queue_test')
    op.drop_table('report_doc')
    op.drop_table('test_i18n_model')
    op.drop_table('mig_doc')
    op.drop_table('dx_artist')
    op.drop_table('test_translation')
    op.drop_index(op.f('test_document_title_idx'), table_name='test_document', postgresql_using='gin')
    op.drop_table('test_document')
    op.drop_table('test_company_model')
    op.drop_table('test_perf_test_tag_rel')
    op.alter_column('ir_actions_act_window', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ir_actions_act_window', 'res_model',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ir_actions_report', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ir_actions_report', 'model',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ir_attachment', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ir_cron', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ir_cron', 'model_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ir_cron', 'method',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ir_cron', 'nextcall',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(op.f('ir_cron_model_id_fkey'), 'ir_cron', type_='foreignkey')
    op.alter_column('ir_model', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ir_model', 'model',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ir_model_access', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ir_model_access', 'model_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('ir_model_access_model_id_fkey'), 'ir_model_access', type_='foreignkey')
    op.drop_constraint(op.f('ir_model_access_group_id_fkey'), 'ir_model_access', type_='foreignkey')
    op.alter_column('ir_model_data', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ir_model_data', 'module',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ir_model_data', 'model',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ir_model_data', 'res_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ir_model_data_module_name_uniq'), table_name='ir_model_data')
    op.alter_column('ir_model_fields', 'model_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ir_model_fields', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ir_model_fields', 'ttype',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('ir_model_fields_model_id_fkey'), 'ir_model_fields', type_='foreignkey')
    op.alter_column('ir_model_fields_group_rel', 'ir_model_fields_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ir_model_fields_group_rel', 'res_groups_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('ir_model_fields_group_rel_ir_model_fields_id_res_groups_id_key'), 'ir_model_fields_group_rel', type_='unique')
    op.drop_constraint(op.f('ir_model_fields_group_rel_ir_model_fields_id_fkey'), 'ir_model_fields_group_rel', type_='foreignkey')
    op.drop_constraint(op.f('ir_model_fields_group_rel_res_groups_id_fkey'), 'ir_model_fields_group_rel', type_='foreignkey')
    op.alter_column('ir_module_module', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ir_rule', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ir_rule', 'model_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('ir_rule_model_id_fkey'), 'ir_rule', type_='foreignkey')
    op.alter_column('ir_rule_res_groups_rel', 'ir_rule_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ir_rule_res_groups_rel', 'res_groups_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('ir_rule_res_groups_rel_ir_rule_id_res_groups_id_key'), 'ir_rule_res_groups_rel', type_='unique')
    op.drop_constraint(op.f('ir_rule_res_groups_rel_ir_rule_id_fkey'), 'ir_rule_res_groups_rel', type_='foreignkey')
    op.drop_constraint(op.f('ir_rule_res_groups_rel_res_groups_id_fkey'), 'ir_rule_res_groups_rel', type_='foreignkey')
    op.alter_column('ir_sequence', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ir_sequence', 'code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('ir_sequence_company_id_fkey'), 'ir_sequence', type_='foreignkey')
    op.alter_column('ir_sequence_date_range', 'sequence_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ir_sequence_date_range', 'date_from',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('ir_sequence_date_range', 'date_to',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_constraint(op.f('ir_sequence_date_range_sequence_id_fkey'), 'ir_sequence_date_range', type_='foreignkey')
    op.alter_column('ir_translation', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ir_translation', 'lang',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ir_ui_menu', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('ir_ui_menu_action_id_fkey'), 'ir_ui_menu', type_='foreignkey')
    op.drop_constraint(op.f('ir_ui_menu_parent_id_fkey'), 'ir_ui_menu', type_='foreignkey')
    op.alter_column('ir_ui_view', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ir_ui_view', 'model',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ir_ui_view', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('ir_ui_view', 'arch',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('ir_ui_view_inherit_id_fkey'), 'ir_ui_view', type_='foreignkey')
    op.alter_column('res_company', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('res_company', 'currency_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('res_company_currency_id_fkey'), 'res_company', type_='foreignkey')
    op.alter_column('res_company_res_users_rel', 'res_users_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('res_company_res_users_rel', 'res_company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('res_company_res_users_rel_res_users_id_res_company_id_key'), 'res_company_res_users_rel', type_='unique')
    op.drop_constraint(op.f('res_company_res_users_rel_res_company_id_fkey'), 'res_company_res_users_rel', type_='foreignkey')
    op.alter_column('res_currency', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('res_currency', 'symbol',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('res_currency_rate', 'currency_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('res_currency_rate', 'name',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_constraint(op.f('res_currency_rate_company_id_fkey'), 'res_currency_rate', type_='foreignkey')
    op.drop_constraint(op.f('res_currency_rate_currency_id_fkey'), 'res_currency_rate', type_='foreignkey')
    op.alter_column('res_groups', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('res_groups_implied_rel', 'gid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('res_groups_implied_rel', 'hid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('res_groups_implied_rel_gid_hid_key'), 'res_groups_implied_rel', type_='unique')
    op.drop_constraint(op.f('res_groups_implied_rel_hid_fkey'), 'res_groups_implied_rel', type_='foreignkey')
    op.drop_constraint(op.f('res_groups_implied_rel_gid_fkey'), 'res_groups_implied_rel', type_='foreignkey')
    op.alter_column('res_groups_res_users_rel', 'res_users_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('res_groups_res_users_rel', 'res_groups_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('res_groups_res_users_rel_res_users_id_res_groups_id_key'), 'res_groups_res_users_rel', type_='unique')
    op.drop_constraint(op.f('res_groups_res_users_rel_res_groups_id_fkey'), 'res_groups_res_users_rel', type_='foreignkey')
    op.alter_column('res_lang', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('res_lang', 'code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('res_partner', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('res_users', 'login',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('res_users_partner_id_fkey'), 'res_users', type_='foreignkey')
    op.drop_constraint(op.f('res_users_company_id_fkey'), 'res_users', type_='foreignkey')
    op.drop_column('res_users', 'name')
    op.alter_column('sale_order', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('sale_order', 'partner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('sale_order_partner_id_fkey'), 'sale_order', type_='foreignkey')
    op.drop_constraint(op.f('sale_order_line_order_id_fkey'), 'sale_order_line', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('sale_order_line_order_id_fkey'), 'sale_order_line', 'sale_order', ['order_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('sale_order_partner_id_fkey'), 'sale_order', 'res_partner', ['partner_id'], ['id'], ondelete='SET NULL')
    op.alter_column('sale_order', 'partner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sale_order', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('res_users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('res_users_company_id_fkey'), 'res_users', 'res_company', ['company_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('res_users_partner_id_fkey'), 'res_users', 'res_partner', ['partner_id'], ['id'], ondelete='SET NULL')
    op.alter_column('res_users', 'login',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('res_partner', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('res_lang', 'code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('res_lang', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(op.f('res_groups_res_users_rel_res_groups_id_fkey'), 'res_groups_res_users_rel', 'res_groups', ['res_groups_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('res_groups_res_users_rel_res_users_id_res_groups_id_key'), 'res_groups_res_users_rel', ['res_users_id', 'res_groups_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('res_groups_res_users_rel', 'res_groups_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('res_groups_res_users_rel', 'res_users_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(op.f('res_groups_implied_rel_gid_fkey'), 'res_groups_implied_rel', 'res_groups', ['gid'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('res_groups_implied_rel_hid_fkey'), 'res_groups_implied_rel', 'res_groups', ['hid'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('res_groups_implied_rel_gid_hid_key'), 'res_groups_implied_rel', ['gid', 'hid'], postgresql_nulls_not_distinct=False)
    op.alter_column('res_groups_implied_rel', 'hid',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('res_groups_implied_rel', 'gid',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('res_groups', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(op.f('res_currency_rate_currency_id_fkey'), 'res_currency_rate', 'res_currency', ['currency_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('res_currency_rate_company_id_fkey'), 'res_currency_rate', 'res_company', ['company_id'], ['id'], ondelete='SET NULL')
    op.alter_column('res_currency_rate', 'name',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('res_currency_rate', 'currency_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('res_currency', 'symbol',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('res_currency', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(op.f('res_company_res_users_rel_res_company_id_fkey'), 'res_company_res_users_rel', 'res_company', ['res_company_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('res_company_res_users_rel_res_users_id_res_company_id_key'), 'res_company_res_users_rel', ['res_users_id', 'res_company_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('res_company_res_users_rel', 'res_company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('res_company_res_users_rel', 'res_users_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(op.f('res_company_currency_id_fkey'), 'res_company', 'res_currency', ['currency_id'], ['id'], ondelete='SET NULL')
    op.alter_column('res_company', 'currency_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('res_company', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(op.f('ir_ui_view_inherit_id_fkey'), 'ir_ui_view', 'ir_ui_view', ['inherit_id'], ['id'], ondelete='SET NULL')
    op.alter_column('ir_ui_view', 'arch',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ir_ui_view', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ir_ui_view', 'model',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ir_ui_view', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(op.f('ir_ui_menu_parent_id_fkey'), 'ir_ui_menu', 'ir_ui_menu', ['parent_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('ir_ui_menu_action_id_fkey'), 'ir_ui_menu', 'ir_actions_act_window', ['action_id'], ['id'], ondelete='SET NULL')
    op.alter_column('ir_ui_menu', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ir_translation', 'lang',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ir_translation', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(op.f('ir_sequence_date_range_sequence_id_fkey'), 'ir_sequence_date_range', 'ir_sequence', ['sequence_id'], ['id'], ondelete='CASCADE')
    op.alter_column('ir_sequence_date_range', 'date_to',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('ir_sequence_date_range', 'date_from',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('ir_sequence_date_range', 'sequence_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(op.f('ir_sequence_company_id_fkey'), 'ir_sequence', 'res_company', ['company_id'], ['id'])
    op.alter_column('ir_sequence', 'code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ir_sequence', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(op.f('ir_rule_res_groups_rel_res_groups_id_fkey'), 'ir_rule_res_groups_rel', 'res_groups', ['res_groups_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('ir_rule_res_groups_rel_ir_rule_id_fkey'), 'ir_rule_res_groups_rel', 'ir_rule', ['ir_rule_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('ir_rule_res_groups_rel_ir_rule_id_res_groups_id_key'), 'ir_rule_res_groups_rel', ['ir_rule_id', 'res_groups_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('ir_rule_res_groups_rel', 'res_groups_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ir_rule_res_groups_rel', 'ir_rule_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(op.f('ir_rule_model_id_fkey'), 'ir_rule', 'ir_model', ['model_id'], ['id'], ondelete='CASCADE')
    op.alter_column('ir_rule', 'model_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ir_rule', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ir_module_module', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(op.f('ir_model_fields_group_rel_res_groups_id_fkey'), 'ir_model_fields_group_rel', 'res_groups', ['res_groups_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('ir_model_fields_group_rel_ir_model_fields_id_fkey'), 'ir_model_fields_group_rel', 'ir_model_fields', ['ir_model_fields_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('ir_model_fields_group_rel_ir_model_fields_id_res_groups_id_key'), 'ir_model_fields_group_rel', ['ir_model_fields_id', 'res_groups_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('ir_model_fields_group_rel', 'res_groups_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ir_model_fields_group_rel', 'ir_model_fields_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(op.f('ir_model_fields_model_id_fkey'), 'ir_model_fields', 'ir_model', ['model_id'], ['id'], ondelete='CASCADE')
    op.alter_column('ir_model_fields', 'ttype',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ir_model_fields', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ir_model_fields', 'model_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ir_model_data_module_name_uniq'), 'ir_model_data', ['module', 'name'], unique=True)
    op.alter_column('ir_model_data', 'res_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ir_model_data', 'model',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ir_model_data', 'module',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ir_model_data', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(op.f('ir_model_access_group_id_fkey'), 'ir_model_access', 'res_groups', ['group_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('ir_model_access_model_id_fkey'), 'ir_model_access', 'ir_model', ['model_id'], ['id'], ondelete='CASCADE')
    op.alter_column('ir_model_access', 'model_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ir_model_access', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ir_model', 'model',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ir_model', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(op.f('ir_cron_model_id_fkey'), 'ir_cron', 'ir_model', ['model_id'], ['id'], ondelete='SET NULL')
    op.alter_column('ir_cron', 'nextcall',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('ir_cron', 'method',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ir_cron', 'model_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ir_cron', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ir_attachment', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ir_actions_report', 'model',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ir_actions_report', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ir_actions_act_window', 'res_model',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('ir_actions_act_window', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_table('test_perf_test_tag_rel',
    sa.Column('test_perf_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('test_tag_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['test_perf_id'], ['test_perf.id'], name=op.f('test_perf_test_tag_rel_test_perf_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_tag_id'], ['test_tag.id'], name=op.f('test_perf_test_tag_rel_test_tag_id_fkey'), ondelete='CASCADE'),
    sa.UniqueConstraint('test_perf_id', 'test_tag_id', name=op.f('test_perf_test_tag_rel_test_perf_id_test_tag_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('test_company_model',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('create_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('write_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['res_company.id'], name=op.f('test_company_model_company_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('test_company_model_pkey'))
    )
    op.create_table('test_document',
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('create_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('write_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('test_document_pkey'))
    )
    op.create_index(op.f('test_document_title_idx'), 'test_document', [sa.literal_column("to_tsvector('spanish'::regconfig, title::text)")], unique=False, postgresql_using='gin')
    op.create_table('test_translation',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('create_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('write_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('test_translation_pkey'))
    )
    op.create_table('dx_artist',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('dx_artist_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('create_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('write_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='dx_artist_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('mig_doc',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('create_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('write_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('new_col', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('mig_doc_pkey'))
    )
    op.create_table('test_i18n_model',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('create_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('write_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('test_i18n_model_pkey'))
    )
    op.create_table('report_doc',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('create_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('write_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('report_doc_pkey'))
    )
    op.create_table('queue_test',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('processed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('create_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('write_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('queue_test_pkey'))
    )
    op.create_table('test_fls',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('secret', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('create_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('write_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('test_fls_pkey'))
    )
    op.create_table('test_perf',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('create_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('write_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('test_perf_pkey'))
    )
    op.create_table('test_realtime',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('create_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('write_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('test_realtime_pkey'))
    )
    op.create_table('perf_record_tag_rel',
    sa.Column('record_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['perf_record.id'], name=op.f('perf_record_tag_rel_record_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['perf_tag.id'], name=op.f('perf_record_tag_rel_tag_id_fkey'), ondelete='CASCADE'),
    sa.UniqueConstraint('record_id', 'tag_id', name=op.f('perf_record_tag_rel_record_id_tag_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('perf_record',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('create_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('write_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('perf_record_pkey'))
    )
    op.create_table('perf_tag',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('create_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('write_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('perf_tag_pkey'))
    )
    op.create_table('rls_doc',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('create_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('write_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('rls_doc_pkey'))
    )
    op.create_table('dx_song',
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('create_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('write_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['dx_artist.id'], name=op.f('dx_song_artist_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('dx_song_pkey'))
    )
    op.create_table('res_partner_test',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('create_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('write_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['res_partner_test.id'], name=op.f('res_partner_test_parent_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('res_partner_test_pkey'))
    )
    op.create_table('test_tag',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('create_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('write_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('test_tag_pkey'))
    )
    op.create_table('test_compute_a',
    sa.Column('x', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('y', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('z', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('create_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('write_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('test_compute_a_pkey'))
    )
    op.create_table('test_i18n_perf',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('create_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('write_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('test_i18n_perf_pkey'))
    )
    # ### end Alembic commands ###
